name: sipm
channels:
  - conda-forge
  - defaults
  - eumetsat
dependencies:
  - jupyter
  - jupyterlab
  - jupyter-server-proxy
  - matplotlib>=3.4
  - notebook
  - numpy
  - pandas
  - pip
  - python=3.8
  - scipy
  - h5py
  - pytables
  - uproot