files:
- /scratch/gpfs/GALBIATI/data/sipm/reflector_studies/2022-11-22/**/*/
script: sipm/exe/fft.py
description: Pre-processing laser calibration data (single photo-electron pulse shape) taken in November 2022 for Tyvek A59 measurements (Liquefaction 2)
arguments:
  num_events: 100000
  calib_file: /home/as111/sipm-analysis/data/calibration_liq2.h5