files:
- /scratch/gpfs/GALBIATI/data/sipm/hamamatsu_test/2023-06-07/*volt_6*/
script: sipm/exe/fft.py
description: Pre-processing liquid nitrogen laser data taken in June 2023 for testing the PCB configuration (Liquefaction 4)
arguments:
  num_events: 295
  calib_file: /home/as111/sipm-analysis/data/calibration_liq4.h5