files:
- /scratch/gpfs/GALBIATI/data/sipm/hamamatsu_test/2023-06-07/*volt_90*/
num_events: 100000
calibration: /home/nwoofter/sipm-analysis/data/calibration_liq4/
script: sipm/exe/laser_waveform_liq4.py
description: Pre-processing liquid nitrogen laser data taken in June 2023 for testing the PCB configuration (Liquefaction 4)