files:
- /scratch/gpfs/GALBIATI/data/sipm/hamamatsu_test/2023-06-07/*volt_9*/
num_events: 100000
script: sipm/exe/laser_pulse.py
description: Pre-processing liquid nitrogen laser data taken in June 2023 for testing the PCB configuration (Liquefaction 4)