files:
- /scratch/gpfs/GALBIATI/data/sipm/hamamatsu_test/2023-11-08/**/*/
script: sipm/exe/laser_pulse.py
description: Pre-processing liquid nitrogen laser data taken for testing the PCB configuration (Liquefaction 4)
arguments:
  num_events: 500000
