files:
- /scratch/gpfs/GALBIATI/data/sipm/hamamatsu_test/2023-07-12/*volt_9*/1/
- /scratch/gpfs/GALBIATI/data/sipm/hamamatsu_test/2023-07-12/*volt_9*/2/
- /scratch/gpfs/GALBIATI/data/sipm/hamamatsu_test/2023-07-12/*volt_9*/3/
- /scratch/gpfs/GALBIATI/data/sipm/hamamatsu_test/2023-07-12/*volt_9*/4/
script: sipm/exe/laser_pulse.py
description: Pre-processing liquid nitrogen laser data taken in July 2023 for testing the PCB configuration (Liquefaction 4)
arguments:
  num_events: 20000
