files:
- /scratch/gpfs/GALBIATI/data/sipm/xenon_doping/2024-05-30/2024-05-30_volt_98_light_scintillation_source_na22_xenon_9_cond_gamma/*/
script: sipm/exe/scintillation_waveform_liq7.py
description: Pre-processing scintillation data (waveform shape) taken in Apr 2024 for xenon doping measurements (Liquefaction 7)
arguments:
  num_events: 100000
  calib_file: /home/as111/sipm-analysis/data/calibration_liq6_2023-12-13.h5
  fprompt:
  - 0.05
  - 0.45
  pe:
  - 15
  - 600
cpu_memory: 32