files:
- /scratch/gpfs/GALBIATI/data/sipm/reflector_studies/*/*pos_bottom*cond_gamma*/*/
- /scratch/gpfs/GALBIATI/data/sipm/reflector_studies/*/*pos_bottom*cond_with_gamma*/*/
cpu_memory: 16
script: sipm/exe/scintillation_waveform.py
description: Pre-processing scintillation data (triplet lifetime evolution, bottom tile) taken in November 2022 for Tyvek A59 measurements (Liquefaction 2)
arguments:
  num_events: 100000
  sipm_calib_dir: /home/as111/sipm-analysis/data/calibration_liq2/
  fprompt:
  - 0.1
  - 0.5
  pe:
  - 100
  - 1000