files:
- /scratch/gpfs/GALBIATI/data/sipm/reflector_studies/*/*pos_top*cond_gamma*/*/
- /scratch/gpfs/GALBIATI/data/sipm/reflector_studies/*/*pos_top*cond_with_gamma*/*/
num_events: 100000
calibration: /home/as111/sipm-analysis/data/calibration_liq2/
fprompt_range:
- 0.1
- 0.5
pe_range:
- 20
- 200
cpu_memory: 16
script: sipm/exe/scintillation_waveform.py
description: Pre-processing scintillation data (triplet lifetime evolution, top tile) taken in November 2022 for Tyvek A59 measurements (Liquefaction 2)