files:
- /scratch/gpfs/GALBIATI/data/sipm/xenon_doping/2024-02-23/*cond_gamma/*/
- /scratch/gpfs/GALBIATI/data/sipm/xenon_doping/2024-02-23/*cond_backgrounds/*/
- /scratch/gpfs/GALBIATI/data/sipm/xenon_doping/2024-03-06/*cond_gamma*/*/
- /scratch/gpfs/GALBIATI/data/sipm/xenon_doping/2024-03-12/*cond_gamma*/*/
- /scratch/gpfs/GALBIATI/data/sipm/xenon_doping/2024-03-19/*cond_gamma*/*/
- /scratch/gpfs/GALBIATI/data/sipm/xenon_doping/2024-03-25/*cond_gamma*/*/
- /scratch/gpfs/GALBIATI/data/sipm/xenon_doping/2024-04-01/*cond_gamma*/*/
script: sipm/exe/scintillation_pulse_liq6.py
description: Pre-processing scintillation data taken in Feb 2024 for xenon doping measurements (Liquefaction 6)
arguments:
  num_events: 100000
  calib_file: /home/as111/sipm-analysis/data/calibration_liq6_2023-12-13.h5
cpu_memory: 32