files:
- /scratch/gpfs/GALBIATI/data/sipm/reflector_studies/2023-05-19/*cond_no_gamma*/*/
script: sipm/exe/scintillation_pulse.py
description: Pre-processing scintillation data taken in April-May 2023 for Tyvek I59 measurements (Liquefaction 3)
arguments:
  num_events: 100000
  sipm_calib_dir: /home/as111/sipm-analysis/data/calibration_liq3/