files:
- /scratch/gpfs/GALBIATI/data/sipm/xenon_doping/2024-05-06/*source_ambe*/*/
script: sipm/exe/scintillation_pulse_liq7.py
description: Pre-processing scintillation data taken in April-May 2024 for xenon doping measurements (Liquefaction 7)
arguments:
  num_events: 100000
  calib_file: /home/as111/sipm-analysis/data/calibration_liq6_2023-12-13.h5
cpu_memory: 32