files:
- /scratch/gpfs/GALBIATI/data/sipm/xenon_doping/2023-12-22/**/*/
script: sipm/exe/scintillation_pulse_liq5.py
description: Pre-processing scintillation data taken in Dec 2023 for xenon doping measurements (Liquefaction 5)
arguments:
  num_events: 100000
  calib_file: /home/as111/sipm-analysis/data/calibration_liq5_2023-12-13.h5
cpu_memory: 32