files:
- /scratch/gpfs/GALBIATI/data/sipm/reflector_studies/2023-05-11/*pos_top*cond_gamma*/*/
cpu_memory: 16
script: sipm/exe/scintillation_waveform.py
description: Pre-processing scintillation data (triplet lifetime evolution, top tile) taken in April-May 2023 for Tyvek I59 measurements (Liquefaction 3)
arguments:
  num_events: 100000
  sipm_calib_dir: /home/as111/sipm-analysis/data/calibration_liq3/
  fprompt:
  - 0
  - 1
  pe:
  - 20
  - 500