files:
- /scratch/gpfs/GALBIATI/data/sipm/xart_long_wf/2025-02-20/2025-02-20_volt_98_light_scintillation_source_na22_cond_monitor/*/
script: sipm/exe/scintillation_waveform_liq8.py
description: Pre-processing scintillation data (waveform shape) taken in Feb-Mar 2025 for XArT long waveform measurements (Liquefaction 8)
arguments:
  num_events: 100000
  calib_file: /scratch/gpfs/GALBIATI/calibration/calibration_liq6_2023-12-13.h5
  fprompt:
  - 0.1
  - 0.6
  pe:
  - 15
  - 400
cpu_memory: 32