files:
- /scratch/gpfs/GALBIATI/data/sipm/xenon_doping/2024-04-19/*cond_monitor*/*/
script: sipm/exe/scintillation_waveform_liq7.py
description: Pre-processing scintillation data (waveform shape) taken in Apr 2024 for xenon doping measurements (Liquefaction 7)
arguments:
  num_events: 100000
  calib_file: /home/as111/sipm-analysis/data/calibration_liq6_2023-12-13.h5
  fprompt:
  - 0.02
  - 0.6
  pe:
  - 10
  - 600
cpu_memory: 32